Remove XAUTHORITY variable from the environment
Setting XAUTHORITY to '$SNAP_REAL_HOME/.Xauthority' causes the
following error on Ubuntu 24.04 with the Wayland windowing system:

  Authorization required, but no authorization protocol specified
  java.awt.AWTError: Can't connect to X11 window server using ':0'
  as the value of the DISPLAY variable.

The error does not occur on Ubuntu 24.04 with X11 nor on Ubuntu 22.04
with either X11 or Wayland because those environments add the current
user name to the list allowed to make connections to the X server:

  ubuntu@ubuntu22:~$ xhost
  access control enabled, only authorized clients can connect
  SI:localuser:ubuntu

while Ubuntu 24.04 with Wayland does not:

  ubuntu@ubuntu24:~$ xhost
  access control enabled, only authorized clients can connect

After this change, you must set the variable manually on the remote
host when using X11 forwarding over SSH:

  export XAUTHORITY=$HOME/.Xauthority

Otherwise, the application fails to start and prints the message:

  X11 connection rejected because of wrong authentication.

See: https://en.wikipedia.org/wiki/X_Window_authorization